# Generated by Django 2.0.6 on 2018-12-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodstype',
            name='category_type',
            field=models.CharField(choices=[('1', '一级类目'), ('2', '二级类目'), ('3', '三级类目')], help_text='类目级别', max_length=30, verbose_name='类目级别'),
        ),
    ]
