# Generated by Django 2.0.6 on 2018-12-26 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20181210_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodstype',
            name='parent_type',
            field=models.ForeignKey(blank=True, help_text='父目录', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='goods.GoodsType', verbose_name='父类目级别'),
        ),
    ]
