# Generated by Django 2.0.6 on 2018-12-07 14:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.IntegerField(default=0, verbose_name='商品数量')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '订单详情',
                'verbose_name_plural': '订单详情',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='订单号')),
                ('trade_num', models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='交易号')),
                ('pay_model', models.CharField(choices=[('qq', 'qq支付'), ('weixin', '微信支付')], default='qq', max_length=30, verbose_name='支付方式')),
                ('pay_status', models.CharField(choices=[('TRADE_SUCCESS', '成功'), ('TRADE_CLOSED', '超时关闭'), ('TRADE_CREATE', '交易创建'), ('TRADE_FINISHED', '交易结束'), ('paying', '待支付')], default='paying', max_length=80, verbose_name='支付状态')),
                ('order_message', models.CharField(max_length=200, verbose_name='订单留言')),
                ('order_money', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='订单金额')),
                ('pay_time', models.DateField(default=datetime.datetime.now, verbose_name='支付时间')),
                ('address', models.CharField(default='', max_length=150, verbose_name='收货地址')),
                ('signer_user', models.CharField(default='', max_length=20, verbose_name='签收人')),
                ('signer_phone', models.CharField(default='', max_length=11, verbose_name='联系电话')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0, verbose_name='购买数量')),
                ('add_time', models.IntegerField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
            },
        ),
    ]
