# Generated by Django 2.0.6 on 2019-01-27 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190121_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
